config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/dashboard', to: 'pages#dashboard'

  resources :groups, only: [:show, :index, :new, :create] do
    resources :trains, only: [:create, :new]
  end
  post '/groups/:id/join', to: 'groups#join'
  post '/groups/:id/leave', to: 'groups#leave'

  resources :sessions, only: [:create]
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  post '/train_options/:id/vote', to: 'votes#create'
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
  has_many :group_users
  has_many :users, through: :group_users
  has_many :trains

  validates :name, uniqueness: true

  def has_user?(user)
    (users + [owner]).include?(user)
  end
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/train.rb
class Train < ActiveRecord::Base
  belongs_to :group
  has_many :train_options
  accepts_nested_attributes_for :train_options, reject_if: proc { |attr| attr['place'].blank? }
  validates :departure_time, presence: true

  MAX_OPTIONS = 4

  def sorted_train_options
    train_options.sort_by(&:vote_count).reverse
  end

  def pretty_time
    departure_time.strftime("%l:%M %P")
  end
end

app/models/train_option.rb
class TrainOption < ActiveRecord::Base
  belongs_to :train
  has_many :votes

  def vote_count
    votes.count
  end

  def yelp_business
    @yelp_business ||= YelpReader.search_for_restaurant(place)
  end

  def yelp_content
    "Rating:  #{yelp_business.rating}
    Phone:  #{yelp_business.display_phone}
    Address:  #{yelp_business.location.address.first}
    Category: #{yelp_business.categories.first.first}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :owned_groups, foreign_key: :owner_id, class_name: "Group"
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :votes

  def self.find_or_create_from_auth_hash(auth_data)
    user = User.where(uid: auth_data['uid']).first_or_create
    user.tap { |u| u.update_attributes full_name: auth_data["info"]["name"] }
  end

  def all_groups
    groups + owned_groups
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :train_option
end

app/models/yelp_reader.rb
class YelpReader
  def self.search_for_restaurant(restaurant)
    # sort is 1 for closest to denver, 0 for best match to term
    search = Yelp.client.search 'Denver', term: restaurant, sort: 1
    search.businesses.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :set_current_user
  helper_method :current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def current_user
    @current_user
  end

  def require_logged_in(path = :back)
    redirect_to path, notice: "You must be logged in to do that" unless current_user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_logged_in, only: [:create, :new, :join, :leave]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.includes(:owner, :users, trains: [train_options: [:votes]]).find_by(id: params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new group_params.merge(owner: current_user)
    if @group.save
      redirect_to group_path(@group), notice: "Group created"
    else
      render :new
    end
  end

  def join
    group = Group.find_by(id: params[:id])
    if group
      group.users << current_user
      redirect_to group_path(group)
    else
      redirect_to :back, notice: "That group you were trying to join doesn't exist"
    end
  end

  def leave
    group = Group.find_by(id: params[:id])
    if group
      group.users -= [current_user]
      redirect_to group_path(group)
    else
      redirect_to :back, notice: "That group you were trying to leave doesn't exist"
    end
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_logged_in, only: [:dashboard]
  def home
    redirect_to dashboard_path if current_user
  end

  def dashboard
    @groups = current_user.all_groups
    @trains = nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = user.id
    redirect_to root_path, notice: "Logged in as #{user.full_name}"
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def create
    @train = Train.new train_params.merge(group_id: params[:group_id])
    @train.save
    redirect_to group_path(params[:group_id])
  end

  def new
    @train = Train.new
    @train_options = Train::MAX_OPTIONS.times.map { TrainOption.new train: @train }
  end

  private
  def train_params
    params.require(:train).permit(:departure_time, train_options_attributes: [:place])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :require_in_group, only: [:create]
  before_action :require_not_yet_voted, only: [:create]
  def create
    train_option = TrainOption.find_by(id: params[:id])
    if train_option
      Vote.where(user: current_user, train_option: train_option.train.train_option_ids).delete_all
      Vote.create(user: current_user, train_option: train_option)
      flash[:notice] = "Vote Placed"
    else
      flash[:notice] = "That option does not exist"
    end
    redirect_to :back
  end

  def require_in_group
    option = TrainOption.find_by(id: params[:id])
    return unless option
    unless option.train.group.has_user? current_user
      redirect_to :back, notice: "you're not in this group"
    end
  end

  def require_not_yet_voted
    if Vote.exists? user: current_user, train_option: params[:id]
      redirect_to :back, notice: "You've already voted"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <center><h1>All Groups</h1></center>
  </div>

  <div class="panel-body">
    <div class="col-md-4 col-md-offset-4">
      <%= render "layouts/groups" %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <center>
      <h1>Create a new group</h1>
    </center>
  </div>
  <div class="panel-body">
    <% @group.errors.full_messages.each do |error| %>
      <%= error %>
    <% end %>
    <%= form_for @group do |f| %>
      <div class="col-md-4 col-md-offset-4">
        <%= f.label :name %><br>
        <%= f.text_field :name %><br><br>
        <%= f.submit class: "btn btn-default btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <center>
    <h1><%= @group.name %></h1>
    <h3>Owner: <%= @group.owner.try(:full_name) %></h3>
    </center>
  </div>



  <div class="panel-body">

  <div class="col-md-4 col-md-offset-1">
    <ul class="list-group">
      <li class="list-group-item"><h2 class="ubuntu">Members</h2></li>
      <% @group.users.each do |user| %>
        <li class="list-group-item"><%= user.full_name %></li>
      <% end %>
    </ul>
    <% if current_user %>
      <% if @group.owner == current_user %>
        <%= button_to "Disband this group", group_path(@group), class: "btn btn-default", method: :delete %>
      <% elsif @group.users.include? current_user %>
        <%= button_to "Leave this group", "/groups/#{@group.id}/leave", class: "btn btn-default", method: :post %>
      <% else %>
        <%= button_to "Join this group", "/groups/#{@group.id}/join", class: "btn btn-default", method: :post %>
      <% end %>
    <% end %>
  </div>


<% @group.trains.each do |train| %>
  <div class="col-md-6 col-md-offset-1">
    <center><h3>Where ya wanna eat bruh?</h3></center>
    <% if train.departure_time %>
      <center><h3>This train leaves at <%= train.pretty_time %></h3></center>
    <% end %>
    <div class="panel panel-default">
      <ul class="list-group">
        <% train.sorted_train_options.each_with_index do |option, index| %>
          <li class="list-group-item vote-group-item">
            <%= button_to "/train_options/#{option.id}/vote", class: "vote-item vote-item-tooltip", method: :post,
            title: option.yelp_content do %>
              Vote for the <%= option.place %> Train <span class="badge"><%= option.vote_count %> votes</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<% if @group.trains.none? %>
  <center><%= link_to "Start a train", new_group_train_path(@group), class: "btn btn-info" %></center>
<% end %>
</div>


</div>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <div class="flash-messages">
    <% flash.each do |key, value| %>
        <h2><%= value %></h2>
    <% end %>
  </div>
<% end %>

app/views/layouts/_groups.html.erb
<center>
  <ul class="list-group">

    <% @groups.each do |group| %>
        <li class="list-group-item"><%= link_to group.name.html_safe, group_path(group), class: "btn btn-lg ubuntu" %></li>
    <% end %>
    <%= link_to "Create a new group", new_group_path, class: "btn btn-success btn-lg", style: "margin:10px 0px;" %>

  </ul>
</center>

app/views/layouts/_header.html.erb
<div class="header-container">
  <nav class="navbar navbar-default navbar-custom-all nav-color-change" role="navigation">
    <div class="navbar-header">
      <%= link_to "Food Train", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-header">
      <%= link_to root_path do %>
        <%= image_tag "train.png", class: "backwards", height: "50px" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li><%= link_to "All Groups", groups_path %></li>
        <% if current_user %>
          <li><a href="<%= logout_path %>"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
        <% else %>
          <li><%= link_to "Log in with yo twits", "/auth/twitter", id: "log-in" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food Train</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if request.path == root_path %>
  <%= yield %>
<% else %>
  <%= render partial: "layouts/header" %>
  <%= render partial: "layouts/flash" %>
  <div class="container">
    <%= yield %>
  </div>
<% end %>


</body>
</html>

app/views/pages/dashboard.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <center>
      <h1>Dashboard</h1>
      <h3></h3>
    </center>
  </div>
  <div class="panel-body">


    <div class="col-md-4">
      <center><h3>Groups I'm In</h3></center>
      <%= render "layouts/groups" %>
    </div>

    <div class="col-md-8">
      <ul class="list-group">
        <li class="list-group-item"><h4>TRAINS ABOUT TO LEAVE</h4></li>
        <li class="list-group-item"><%= link_to "Pizza Train - Turing 1409", "#", class: "btn" %></li>
        <li class="list-group-item"><%= link_to "Web Design Train - Turing 1408", "#", class: "btn" %></li>
      </ul>
    </div>


  </div>
</div>

app/views/pages/home.html.erb
<% if flash.any? %>
  <div class="splash-window splash-window-flash">
    <%= render partial: "layouts/flash" %>
  </div>
<% end %>
<div class="splash-window splash-window-main">
  <h1>Food Train</h1>
  <h2>Clever Tagline</h2>
  <%= link_to "Sign in with Twitter", "/auth/twitter", class: "btn btn-lg btn-default", id: "log-in" %>
</div>

app/views/trains/new.html.erb
<div class="panel panel-info">
  <div class="panel-header">
    <center><h1>Start a train</h1></center>
  </div>
  <div class="panel-body">
    <div class="col-md-4 col-md-offset-4">
      <%= form_for @train, url: group_trains_path do |f| %>
        <%= f.fields_for :train_options, @train_options do |ff| %>
          <h4>Option <%= ff.options[:child_index] + 1 %></h4>
          <%= ff.text_field :place %>
        <% end %>
        <input type="time" name="train[departure_time]" value="">
        <%= f.submit "Start the train", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>